# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9ciGOygqCoyY5est5y8UBj40gVM1gBT

# **Bem-vindo à calculadora simplificada 4 operações!**
"""

nome = input("Digite seu nome")
print(nome)

while True: # Loop para repetir as operações enquanto o usuário quiser

    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    # Escolha da operação
    print("Escolha a operação desejada:")
    print("1: Soma (+)")
    print("2: Subtração (-)")
    print("3: Multiplicação (*)")
    print("4: Divisão (/)")
    print("5: Potência (**)")
    print("6: Porcentagem (%)")
    operacao = input("Digite o número da operação: ")

    # Executando a operação escolhida
    if operacao == "1":
        resultado = num1 + num2
        print("Resultado da soma:", resultado)
    elif operacao == "2":
        resultado = num1 - num2
        print("Resultado da subtração:", resultado)
    elif operacao == "3":
        resultado = num1 * num2
        print("Resultado da multiplicação:", resultado)
    elif operacao == "4":
        if num2 != 0:
            resultado = num1 / num2
            print("Resultado da divisão:", resultado)
        else:
            print("Erro: divisão por zero não é permitida.")
    elif operacao == "5":
        resultado = num1 ** num2
        print("Resultado da potência:", resultado)
    elif operacao == "6":
        resultado = (num2 / num1) * 100
        print("Resultado da porcentagem:", resultado)
    else:
        print("Operação inválida.")

    # Pergunta se o usuário quer fazer outra operação
    repetir = input("Deseja fazer outra operação? (s para sim / qualquer outra tecla para sair): ")
    if repetir.lower() != "s":
        print("Obrigado por usar a calculadora. Até a próxima!")
        break
